# Generated by Django 3.0.5 on 2020-05-06 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_title', models.CharField(max_length=20)),
                ('idea_subtitle', models.TextField(max_length=100)),
                ('idea_image', models.ImageField(blank=True, default='.png', null=True, upload_to='')),
                ('idea_description', models.TextField(max_length=500)),
                ('idea_hashtag', models.TextField(max_length=100)),
                ('idea_likecount', models.IntegerField(blank=True, null=True)),
                ('idea_create_data', models.DateTimeField(blank=True, default='2020/05/06', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image_storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('idea_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.Idea')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('create_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='idea.Idea')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AddComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('create_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.Comment')),
            ],
        ),
    ]
