# Generated by Django 3.0.5 on 2020-05-04 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signIn', '0001_initial'),
        ('ideaDetail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_title', models.CharField(max_length=20)),
                ('idea_subtitle', models.TextField(max_length=100)),
                ('idea_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('idea_description', models.TextField(max_length=500)),
                ('idea_hashtag', models.TextField(max_length=100)),
                ('idea_likecount', models.IntegerField()),
                ('idea_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideaDetail.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signIn.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Image_storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('idea_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.Idea')),
            ],
        ),
    ]
