# Generated by Django 3.0.5 on 2020-05-04 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('idea_pk', models.AutoField(primary_key=True, serialize=False)),
                ('idea_title', models.CharField(max_length=20)),
                ('idea_subtitle', models.TextField(max_length=100)),
                ('idea_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('idea_description', models.TextField(max_length=500)),
                ('idea_hashtag', models.TextField(max_length=100)),
                ('idea_likecount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image_storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('idea_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.Idea')),
            ],
        ),
    ]
