# Generated by Django 3.0.5 on 2020-05-06 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='user_school',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_create_data',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_hashtag',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_subtitle',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
