# Generated by Django 3.0.5 on 2020-05-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea_image',
            field=models.ImageField(blank=True, null=True, upload_to='idea/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='idea_image_storage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='idea/%Y%m%d'),
        ),
    ]
