# Generated by Django 3.0.5 on 2020-05-08 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Idea',
            new_name='Idea1',
        ),
        migrations.RenameModel(
            old_name='Idea_Comments',
            new_name='Idea_AddComments1',
        ),
        migrations.RenameModel(
            old_name='Idea_AddComments',
            new_name='Idea_Comments1',
        ),
        migrations.RenameModel(
            old_name='Idea_image_storage',
            new_name='Idea_image_storage1',
        ),
        migrations.RemoveField(
            model_name='idea_addcomments1',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='idea_comments1',
            name='idea_comments',
        ),
        migrations.AddField(
            model_name='idea_addcomments1',
            name='idea_comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.Idea_Comments1'),
        ),
        migrations.AddField(
            model_name='idea_comments1',
            name='idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.Idea1'),
        ),
    ]
