# Generated by Django 3.0.5 on 2020-05-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_auto_20200518_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea_likecount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
