# Generated by Django 3.0.5 on 2020-05-29 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_auto_20200529_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea_image_storage',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.Idea'),
        ),
    ]
