# Generated by Django 3.0.5 on 2020-05-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_auto_20200530_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea_image',
            field=models.ImageField(blank=True, null=True, upload_to='idea/%Y%m%d/thumbnail'),
        ),
    ]
