# Generated by Django 3.0.5 on 2020-05-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signIn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea_cart',
            name='save',
            field=models.NullBooleanField(),
        ),
    ]
