# Generated by Django 3.0.5 on 2020-05-19 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signIn', '0002_idea_cart_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea_cart',
            old_name='save',
            new_name='add_cart',
        ),
    ]
