# Generated by Django 3.0.5 on 2020-05-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signIn', '0004_auto_20200520_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(blank=True, default='idea/static/image/lion.png', null=True, upload_to='signIn/static/profile'),
        ),
    ]
