<<<<<<< HEAD:accounts/migrations/0002_auto_20200526_1240.py
# Generated by Django 3.0.5 on 2020-05-26 03:40
=======
# Generated by Django 3.0.5 on 2020-05-26 03:48
>>>>>>> 8df512c0f5f3c2f1e9db16299bac9fc786bb4a7d:accounts/migrations/0002_auto_20200526_1248.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD:accounts/migrations/0002_auto_20200526_1240.py
        ('idea', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
=======
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0001_initial'),
        ('idea', '0001_initial'),
>>>>>>> 8df512c0f5f3c2f1e9db16299bac9fc786bb4a7d:accounts/migrations/0002_auto_20200526_1248.py
    ]

    operations = [
        migrations.AddField(
            model_name='idea_cart',
            name='idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.Idea'),
        ),
        migrations.AddField(
            model_name='idea_cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
