# Generated by Django 3.0.5 on 2020-05-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideaDetail', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddComment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
