# Generated by Django 3.0.5 on 2020-05-01 14:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideaDetail', '0002_comment_create_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('create_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ideaDetail.Comment')),
            ],
        ),
    ]
