# Generated by Django 3.0.5 on 2020-05-01 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideaDetail', '0003_addcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcomment',
            old_name='comment_pk',
            new_name='comment',
        ),
    ]
