# Generated by Django 3.0.5 on 2020-05-01 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideaDetail', '0005_remove_addcomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcomment',
            name='add_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addcomment',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ideaDetail.Comment'),
        ),
    ]
