# Generated by Django 3.0.5 on 2020-05-01 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideaDetail', '0007_auto_20200502_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcomment',
            name='comment_pk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ideaDetail.Comment'),
        ),
    ]
