# Generated by Django 3.0.5 on 2020-05-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideaDetail', '0008_addcomment_comment_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_pk',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
